# Generated by Django 5.0.3 on 2024-12-02 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 14, 30, 40, 475002)),
        ),
    ]
